services:

  nginx:
    image: nginx
    volumes:
      - ./docker/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/app
    ports:
      - 80:80
    depends_on:
      - php

  php:
    image: php:8.3-fpm
    volumes:
      - .:/app

